# This is a basic workflow to help you get started with Actions

name: Snake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.reactions.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      - name: Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.traffic.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: repositories
          plugin_traffic: yes

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push metrics SVGs to the metrics branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: metrics
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
